
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Tennis_Training?serverTimezone=UTC?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123


Logging:
  level:
    com.wms: debug